support_mart:
    brg: true
    dmx: true
    nova: true
    emart: true
    hc: true
    lamthao: true
    nuty: true
    tgsf: true
    711: true
    bhx: true
    bigc: true
    gs25: true
    vinmart: true
    topmarket: true
    coopmart: true
    mega: true
    lotte: true
    aeon: true
    aeoncitimart: true
    tgs: true
    satra: true
    lanchi: true
    guardian: true
    nguyenkim: true
    fujimart: true
    heineken: true
    go: true
    coopxtra: true
    familymart: true

support_rules:
    FR001: true
    SP001: true
    IQ002: true
    IQ003: true
    IQ004: true
    IT001: true
    IT002: true
    IL001: true
    IL002: true
    IL003: true